### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by siokstoksanoks** [react-native-community/react-native-async-storage#43]
## You want to:  
Hi, is there any proguard rules for android?

## Details:
No info provided about proguard rules

**Comment by Krizzu** [comment]
Hi @siokstoksanoks 	

Anything specific you're experiencing? Crashes in production maybe?
[React Native has its own proguard Rules](https://github.com/facebook/react-native/blob/master/ReactAndroid/proguard-rules.pro)

**Comment by siokstoksanoks** [comment]
No no problem yet, question is general. 

Whats inside react-native proguard is for react-native. 
Every native library provides its own rules if they are needed.

If no rules are needed it has to mentioned.

**Comment by Krizzu** [comment]
@siokstoksanoks Hey, could you elaborate bit more about it?
I mentioned that this library uses RN's proguard, because it covers its basic usages.

We're not mentioning any proguard settings, because it does not need any extra step. Unless someone will get an error regarding it, we can fix and document necessary work.

Closing this issue for now, let me know if further discussion is needed.

Thanks.
