### ISSUE TITLE
Why 6mb dataset size for android?

### ISSUE THREAD

**Issue by Nthalk** [react-native-community/react-native-async-storage#83]
I want to know why we carry forward a non-configurable, arbitrary value (6mb) for the maximum database size for Android, while leaving IOS unlimited.

Especially when I'll just get around this with JSON stringify and react-native-sqlite-storage.

https://github.com/react-native-community/react-native-async-storage/blob/c57cbeb25034c4291cc148084ad3933266daf641/android/src/main/java/com/reactnativecommunity/asyncstorage/ReactDatabaseSupplier.java#L46

**Comment by Krizzu** [comment]
Hey @Nthalk,

We did not change the initial limit, because of [a note left from original creators](https://github.com/react-native-community/react-native-async-storage/blob/c57cbeb25034c4291cc148084ad3933266daf641/android/src/main/java/com/reactnativecommunity/asyncstorage/ReactDatabaseSupplier.java#L103-L105). I'm not quite sure if it's still relevant or not, but I think we could let this value be set from user (for example, a new limit passed as argument to `AsyncStorage` package in `MainApplication`.

[FYI, here are limits of SQLite DB.](https://www.sqlite.org/limits.html)


thanks.

**Comment by tido64** [comment]
I'm closing this issue since we've just merged a change to make this limit configurable. Please try it out and let us know how you go.
